##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - cppcheck
    - curl

variables:
  - 'CHECKIDS="warning,style,performance,portability,information,missingInclude"'

build_scripts:
  - cppcheck --enable=$CHECKIDS --force -j $CPU_COUNT .
  - cppcheck --xml --output-file=cppcheck.xml --enable=$CHECKIDS . &> /dev/null
  - cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=galc_cppcheck-htmlreport --source-encoding="iso8859-1" &> /dev/null
  - tar -zcf galc_cppcheck-htmlreport.tar.gz galc_cppcheck-htmlreport
  - curl -F file=@galc_cppcheck-htmlreport.tar.gz -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
