##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/atril
    - debhelper 
    - dh-autoreconf
    - flex
    - gettext
    - intltool
    - libgtk-3-dev
    - libxml-parser-perl

build_scripts:
   - cd ..
   - ls -la
#  - NOCONFIGURE=1 ./autogen.sh
#  - scan-build $CHECKERS ./configure
#  - scan-build $CHECKERS --keep-cc -o galc_clang_htmlreport make -j $CPU_COUNT
#  - tar -zcf galc_clang_htmlreport.tar.gz galc_clang_htmlreport
#  - curl -F file=@galc_clang_htmlreport.tar.gz -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo

#after_scripts:
#  - make check
#  - make distcheck
#  - make clean
#  - make distclean
