dist: bionic
language: shell
os: linux
services:
  - docker
addons:
  apt:
    packages:
      - python3-github

env:
  - JOB=cppcheckTest DISTRO="debian:testing"
  - JOB=clangTest DISTRO="debian:buster"

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - ./docker-build --name ${DISTRO} --config .$JOB.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .$JOB.yml --build scripts
